export const CREATE_ADDRESS = "CREATE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const FETCH_ADDRESS = "FETCH_ADDRESS";
export const FETCH_ADDRESSES = "FETCH_ADDRESSES";
