export const FETCH_REQUESTS = "FETCH_REQUESTS";
export const APPROVE_REQUEST = "APPROVE_REQUEST";
export const REJECT_REQUEST = "REJECT_REQUEST";
export const DELIVER_REQUEST = "DELIVER_REQUEST";
