export const CREATE_REVIEW = "CREATE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const FETCH_REVIEW = "FETCH_REVIEW";
export const FETCH_REVIEWS = "FETCH_REVIEWS";
